#!/bin/bash
# pullback-tune boot script — generated by tune-install.sh
# Applied on every boot via systemd.

TAG="pullback-tune"
log() { logger -t "$TAG" "$*"; }

# RPS: distribute network softirqs
if [[ -f /sys/class/net/eth0/queues/rx-0/rps_cpus ]]; then
    echo c > /sys/class/net/eth0/queues/rx-0/rps_cpus
    log "RPS enabled on CPU2+3"
fi
if [[ -f /proc/sys/net/core/rps_sock_flow_entries ]]; then
    echo 32768 > /proc/sys/net/core/rps_sock_flow_entries
    log "RPS flow entries set"
fi
# Disable EEE (Energy Efficient Ethernet)
if command -v ethtool &>/dev/null; then
    ethtool --set-eee eth0 eee off 2>/dev/null && \
        log "EEE disabled" || \
        log "EEE not supported (ok)"
fi
# CPU governor
for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    if [[ -f "$gov" ]]; then
        echo performance > "$gov"
    fi
done
log "CPU governor set to performance"
