#!/bin/bash
# tune-install.sh — Install persistent performance tuning from config.yaml.
# Writes sysctl config and creates a systemd oneshot for non-sysctl settings.
# Run once on the target machine as root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG="${PROJECT_DIR}/config.yaml"

SYSCTL_DST="/etc/sysctl.d/99-pullback.conf"
SERVICE_NAME="pullback-tune"
SERVICE_DST="/etc/systemd/system/${SERVICE_NAME}.service"
TUNE_SCRIPT="${SCRIPT_DIR}/pi-tune-boot.sh"

if [[ $EUID -ne 0 ]]; then
    echo "Error: must run as root" >&2
    exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
    echo "Error: config.yaml not found at ${CONFIG}" >&2
    exit 1
fi

# ── Read tuning values from config.yaml ──

get_val() {
    grep "^\s*$1:" "$CONFIG" | awk '{print $2}' | head -1
}

DIRTY_RATIO=$(get_val dirty_ratio)
DIRTY_BG=$(get_val dirty_background_ratio)
DIRTY_EXPIRE=$(get_val dirty_expire_centisecs)
DIRTY_WRITEBACK=$(get_val dirty_writeback_centisecs)
RPS_ENABLED=$(get_val rps_enabled)
EEE_OFF=$(get_val eee_off)
CPU_GOV=$(get_val cpu_governor)
UAS_ENABLED=$(get_val uas)

: "${DIRTY_RATIO:=5}"
: "${DIRTY_BG:=2}"
: "${DIRTY_EXPIRE:=1000}"
: "${DIRTY_WRITEBACK:=500}"
: "${UAS_ENABLED:=false}"
: "${RPS_ENABLED:=true}"
: "${EEE_OFF:=true}"
: "${CPU_GOV:=performance}"

# ── Write sysctl config (persists automatically) ──

cat > "$SYSCTL_DST" <<EOF
# pullback performance tuning — generated by tune-install.sh
vm.dirty_ratio = ${DIRTY_RATIO}
vm.dirty_background_ratio = ${DIRTY_BG}
vm.dirty_expire_centisecs = ${DIRTY_EXPIRE}
vm.dirty_writeback_centisecs = ${DIRTY_WRITEBACK}
EOF

sysctl --load="$SYSCTL_DST" >/dev/null 2>&1
echo "Installed: ${SYSCTL_DST}"
echo "  dirty_ratio=${DIRTY_RATIO} dirty_bg=${DIRTY_BG} expire=${DIRTY_EXPIRE} writeback=${DIRTY_WRITEBACK}"

# ── Generate boot script for non-sysctl settings ──

cat > "$TUNE_SCRIPT" <<BOOTEOF
#!/bin/bash
# pullback-tune boot script — generated by tune-install.sh
# Applied on every boot via systemd.

TAG="pullback-tune"
log() { logger -t "\$TAG" "\$*"; }

BOOTEOF

if [[ "$RPS_ENABLED" == "true" ]]; then
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
# RPS: distribute network softirqs
if [[ -f /sys/class/net/eth0/queues/rx-0/rps_cpus ]]; then
    echo c > /sys/class/net/eth0/queues/rx-0/rps_cpus
    log "RPS enabled on CPU2+3"
fi
if [[ -f /proc/sys/net/core/rps_sock_flow_entries ]]; then
    echo 32768 > /proc/sys/net/core/rps_sock_flow_entries
    log "RPS flow entries set"
fi
BOOTEOF
fi

if [[ "$EEE_OFF" == "true" ]]; then
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
# Disable EEE (Energy Efficient Ethernet)
if command -v ethtool &>/dev/null; then
    ethtool --set-eee eth0 eee off 2>/dev/null && \
        log "EEE disabled" || \
        log "EEE not supported (ok)"
fi
BOOTEOF
fi

if [[ -n "$CPU_GOV" ]]; then
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
# CPU governor
for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    if [[ -f "$gov" ]]; then
BOOTEOF
    echo "        echo ${CPU_GOV} > \"\$gov\"" >> "$TUNE_SCRIPT"
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
    fi
done
BOOTEOF
    echo "log \"CPU governor set to ${CPU_GOV}\"" >> "$TUNE_SCRIPT"
fi

chmod +x "$TUNE_SCRIPT"
echo "Generated: ${TUNE_SCRIPT}"

# ── UAS: force USB Attached SCSI for backup drive ──

if [[ "$UAS_ENABLED" == "true" ]]; then
    CMDLINE="/boot/firmware/cmdline.txt"
    if [[ ! -f "$CMDLINE" ]]; then
        CMDLINE="/boot/cmdline.txt"
    fi

    if [[ -f "$CMDLINE" ]]; then
        # Auto-detect USB mass storage device
        USB_ID=$(lsusb | grep -i -E 'mass storage|external|canvio|seagate|wd|toshiba|hitachi|backup' | head -1 | grep -oP '\b[0-9a-f]{4}:[0-9a-f]{4}\b')

        if [[ -z "$USB_ID" ]]; then
            # Fallback: find any USB storage device on bus 002 (USB 3.0)
            USB_ID=$(lsusb -t | grep -A1 'Bus 002' | grep 'Mass Storage' -B1 | head -1)
            USB_ID=$(lsusb | grep 'Bus 002' | grep -v 'root hub' | head -1 | grep -oP '\b[0-9a-f]{4}:[0-9a-f]{4}\b')
        fi

        if [[ -n "$USB_ID" ]]; then
            # Check if drive actually supports UAS (has UAS interface)
            HAS_UAS=$(lsusb -v -d "$USB_ID" 2>/dev/null | grep -c 'bInterfaceProtocol.*UAS\|bInterfaceSubClass.*6.*SCSI' || true)
            PROTO=$(lsusb -v -d "$USB_ID" 2>/dev/null | grep 'bInterfaceProtocol' | head -1 | awk '{print $NF}')

            if [[ "$PROTO" == "Bulk-Only" ]]; then
                echo "USB device ${USB_ID} uses Bulk-Only transport — UAS not supported by this drive"
                echo "  No changes made. UAS requires a drive with a UAS-capable USB-SATA bridge."
                # Remove any stale quirk
                sed -i "s| usb-storage.quirks=[0-9a-f:]*:u||g" "$CMDLINE"
            else
                QUIRK="usb-storage.quirks=${USB_ID}:u"
                # Remove any existing pullback UAS quirk
                sed -i "s| usb-storage.quirks=[0-9a-f:]*:u||g" "$CMDLINE"
                # Add new quirk
                sed -i "s|rootwait|rootwait ${QUIRK}|" "$CMDLINE"
                echo "UAS enabled for USB device ${USB_ID}"
                echo "  Added to ${CMDLINE}: ${QUIRK}"
                echo "  *** REBOOT REQUIRED for UAS to take effect ***"
            fi
        else
            echo "WARNING: No USB storage device detected — UAS not configured"
        fi
    else
        echo "WARNING: cmdline.txt not found — UAS not configured"
    fi
fi

# ── Create systemd service ──

cat > "$SERVICE_DST" <<EOF
[Unit]
Description=pullback performance tuning
After=network.target

[Service]
Type=oneshot
ExecStart=${TUNE_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

echo "Installed: ${SERVICE_DST}"

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"

echo "Service ${SERVICE_NAME} started and enabled on boot."
echo ""
echo "Current values:"
sysctl vm.dirty_ratio vm.dirty_background_ratio vm.dirty_expire_centisecs vm.dirty_writeback_centisecs
