#!/bin/bash
# pi-tune-install.sh — Install persistent performance tuning from merged config.
# Reads config.yaml + config.local.yaml via Python (respects local overrides).
# Writes sysctl config and creates a systemd oneshot for non-sysctl settings.
# Run as root on the target machine.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENV_PYTHON="${PROJECT_DIR}/venv/bin/python3"

SYSCTL_DST="/etc/sysctl.d/99-pullback.conf"
SERVICE_NAME="pullback-tune"
SERVICE_DST="/etc/systemd/system/${SERVICE_NAME}.service"
TUNE_SCRIPT="${SCRIPT_DIR}/pi-tune-boot.sh"

if [[ $EUID -ne 0 ]]; then
    echo "Error: must run as root" >&2
    exit 1
fi

if [[ ! -f "$VENV_PYTHON" ]]; then
    echo "Error: venv not found at ${VENV_PYTHON} — run pyenv-setup.sh first" >&2
    exit 1
fi

# ── Read merged config via Python ──

read_cfg() {
    "$VENV_PYTHON" -c "
from config import load_config
cfg = load_config()
t = cfg.get('tuning', {})
u = cfg.get('usb', {})
print(f'dirty_ratio={t.get(\"dirty_ratio\", 5)}')
print(f'dirty_background_ratio={t.get(\"dirty_background_ratio\", 2)}')
print(f'dirty_expire_centisecs={t.get(\"dirty_expire_centisecs\", 1000)}')
print(f'dirty_writeback_centisecs={t.get(\"dirty_writeback_centisecs\", 500)}')
print(f'bdi_max_bytes={t.get(\"bdi_max_bytes\", 0)}')
print(f'rps_enabled={str(t.get(\"rps_enabled\", True)).lower()}')
print(f'eee_off={str(t.get(\"eee_off\", True)).lower()}')
print(f'cpu_governor={t.get(\"cpu_governor\", \"performance\")}')
print(f'uas={str(u.get(\"uas\", False)).lower()}')
" 2>&1
}

# Run from project dir so imports work
cd "$PROJECT_DIR"
CFG_OUTPUT=$(read_cfg)
if [[ $? -ne 0 ]]; then
    echo "Error reading config:" >&2
    echo "$CFG_OUTPUT" >&2
    exit 1
fi

# Parse into variables
eval "$CFG_OUTPUT"

echo ""
echo "=== Config (merged) ==="
echo "  dirty_ratio            = ${dirty_ratio}"
echo "  dirty_background_ratio = ${dirty_background_ratio}"
echo "  dirty_expire_centisecs = ${dirty_expire_centisecs}"
echo "  dirty_writeback_centisecs = ${dirty_writeback_centisecs}"
echo "  bdi_max_bytes          = ${bdi_max_bytes}"
echo "  rps_enabled            = ${rps_enabled}"
echo "  eee_off                = ${eee_off}"
echo "  cpu_governor           = ${cpu_governor}"
echo "  uas                    = ${uas}"
echo ""

# ── Write sysctl config (persists automatically) ──

cat > "$SYSCTL_DST" <<EOF
# pullback performance tuning — generated by pi-tune-install.sh
vm.dirty_ratio = ${dirty_ratio}
vm.dirty_background_ratio = ${dirty_background_ratio}
vm.dirty_expire_centisecs = ${dirty_expire_centisecs}
vm.dirty_writeback_centisecs = ${dirty_writeback_centisecs}
EOF

sysctl --load="$SYSCTL_DST" >/dev/null 2>&1
echo "Installed: ${SYSCTL_DST}"

# ── Generate boot script for non-sysctl settings ──

cat > "$TUNE_SCRIPT" <<BOOTEOF
#!/bin/bash
# pullback-tune boot script — generated by pi-tune-install.sh
# Applied on every boot via systemd.

TAG="pullback-tune"
log() { logger -t "\$TAG" "\$*"; }

BOOTEOF

if [[ "$rps_enabled" == "true" ]]; then
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
# RPS: distribute network softirqs
if [[ -f /sys/class/net/eth0/queues/rx-0/rps_cpus ]]; then
    echo c > /sys/class/net/eth0/queues/rx-0/rps_cpus
    log "RPS enabled on CPU2+3"
fi
if [[ -f /proc/sys/net/core/rps_sock_flow_entries ]]; then
    echo 32768 > /proc/sys/net/core/rps_sock_flow_entries
    log "RPS flow entries set"
fi
BOOTEOF
fi

if [[ "$eee_off" == "true" ]]; then
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
# Disable EEE (Energy Efficient Ethernet)
if command -v ethtool &>/dev/null; then
    ethtool --set-eee eth0 eee off 2>/dev/null && \
        log "EEE disabled" || \
        log "EEE not supported (ok)"
fi
BOOTEOF
fi

if [[ -n "$cpu_governor" ]]; then
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
# CPU governor
for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    if [[ -f "$gov" ]]; then
BOOTEOF
    echo "        echo ${cpu_governor} > \"\$gov\"" >> "$TUNE_SCRIPT"
    cat >> "$TUNE_SCRIPT" <<'BOOTEOF'
    fi
done
BOOTEOF
    echo "log \"CPU governor set to ${cpu_governor}\"" >> "$TUNE_SCRIPT"
fi

if [[ "$bdi_max_bytes" -gt 0 ]] 2>/dev/null; then
    cat >> "$TUNE_SCRIPT" <<BOOTEOF
# BDI: per-device dirty page limit for backup drive
MOUNT_POINT=\$(awk '/\\/backup/{print \$1}' /proc/mounts | head -1)
if [[ -n "\$MOUNT_POINT" ]]; then
    BDI_DEV=\$(basename "\$MOUNT_POINT" | sed 's/[0-9]*$//')
    if [[ -f "/sys/block/\${BDI_DEV}/bdi/strict_limit" ]]; then
        echo 1 > /sys/block/\${BDI_DEV}/bdi/strict_limit
        echo ${bdi_max_bytes} > /sys/block/\${BDI_DEV}/bdi/max_bytes
        log "BDI strict_limit=1 max_bytes=${bdi_max_bytes} on \${BDI_DEV}"
    else
        log "BDI sysfs not available for \${BDI_DEV}"
    fi
else
    log "BDI: /backup not mounted, skipping"
fi
BOOTEOF
fi

chmod +x "$TUNE_SCRIPT"
echo "Generated: ${TUNE_SCRIPT}"

# ── UAS: force USB Attached SCSI for backup drive ──

if [[ "$uas" == "true" ]]; then
    CMDLINE="/boot/firmware/cmdline.txt"
    if [[ ! -f "$CMDLINE" ]]; then
        CMDLINE="/boot/cmdline.txt"
    fi

    if [[ -f "$CMDLINE" ]]; then
        USB_ID=$(lsusb | grep -i -E 'mass storage|external|canvio|seagate|wd|toshiba|hitachi|backup' | head -1 | grep -oP '\b[0-9a-f]{4}:[0-9a-f]{4}\b' || true)

        if [[ -z "$USB_ID" ]]; then
            USB_ID=$(lsusb | grep 'Bus 002' | grep -v 'root hub' | head -1 | grep -oP '\b[0-9a-f]{4}:[0-9a-f]{4}\b' || true)
        fi

        if [[ -n "$USB_ID" ]]; then
            PROTO=$(lsusb -v -d "$USB_ID" 2>/dev/null | grep 'bInterfaceProtocol' | head -1 | awk '{print $NF}')

            if [[ "$PROTO" == "Bulk-Only" ]]; then
                echo "UAS: ${USB_ID} Bulk-Only — not supported"
                sed -i "s| usb-storage.quirks=[0-9a-f:]*:u||g" "$CMDLINE"
            else
                QUIRK="usb-storage.quirks=${USB_ID}:u"
                sed -i "s| usb-storage.quirks=[0-9a-f:]*:u||g" "$CMDLINE"
                sed -i "s|rootwait|rootwait ${QUIRK}|" "$CMDLINE"
                echo "UAS: enabled for ${USB_ID} — REBOOT REQUIRED"
            fi
        else
            echo "UAS: no USB storage device detected"
        fi
    else
        echo "UAS: cmdline.txt not found"
    fi
fi

# ── Create systemd service ──

cat > "$SERVICE_DST" <<EOF
[Unit]
Description=pullback performance tuning
After=network.target

[Service]
Type=oneshot
ExecStart=${TUNE_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"
echo "Installed: ${SERVICE_DST}"

# ── Summary ──

echo ""
echo "=== Applied ==="
sysctl vm.dirty_ratio vm.dirty_background_ratio vm.dirty_expire_centisecs vm.dirty_writeback_centisecs 2>/dev/null | sed 's/^/  /'
DISK_DEV=$(df /backup 2>/dev/null | tail -1 | awk '{print $1}' | xargs basename 2>/dev/null | sed 's/[0-9]*$//' || echo "")
if [[ -n "$DISK_DEV" && -f "/sys/block/${DISK_DEV}/bdi/strict_limit" ]]; then
    echo "  BDI (${DISK_DEV}): strict_limit=$(cat /sys/block/${DISK_DEV}/bdi/strict_limit) max_bytes=$(cat /sys/block/${DISK_DEV}/bdi/max_bytes)"
fi
echo "  governor: $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null)"
echo "  RPS: $(cat /sys/class/net/eth0/queues/rx-0/rps_cpus 2>/dev/null)"
EEE=$(ethtool --show-eee eth0 2>/dev/null | grep -i 'eee status' | awk -F: '{print $2}' | xargs)
echo "  EEE: ${EEE:-n/a}"
echo ""
